### ISSUE TITLE
Add the currency icon next to its name in the table

### ISSUE THREAD

**Issue by kazazor** [kazazor/coinsmarket#18]
<img width="160" alt="screen shot 2017-06-17 at 3 59 08 am" src="https://user-images.githubusercontent.com/1577655/27248800-582b1f60-5311-11e7-8b01-91ba29f5938b.png">

**Comment by kazazor** [comment]
Is blocked by: https://github.com/kazazor/coinsmarket/issues/52

**Comment by OmriAharon** [comment]
This information isn't returned from the API, what did you have in mind?

**Comment by kazazor** [comment]
two options:
1. A different API that does return it.. Saw some other API providers.. I think they can be found here: #67 
2. Get the images of all these coins and add them to the project

**Comment by kazazor** [comment]
I was thinking about: https://www.cryptocompare.com/api/data/coinlist/

P.S:
If we do add them, we have to add their link and thank you to the website.. Part of the term of usage..
