### ISSUE TITLE
API calls to get the data are still being triggered even if the privous one hasn't been completed yet

### ISSUE THREAD

**Issue by kazazor** [kazazor/coinsmarket#74]
I noticed it on slow wifi on the train. COuld be a little bit bad for mobile with slow connection.
Maybe we should check if the last 1 finished or not before making another one..

@OmriAharon - WDYT?

**Comment by OmriAharon** [comment]
Interesting... Could maybe keep a timestamp on the return call and then start the count.

**Comment by kazazor** [comment]
Pay attention that this won't work in case of error / timeouts.. Needs to also have a timestamp on that..

**Comment by kazazor** [comment]
OK a better idea - add to the store `isUpdatingData`.
In the `coinsApisService` just don't do anything in the interval while `isUpdatingData` is `true`.
That way it'll all be dynamic and be ok :)
All you have to is `FETCH_COINS_FRONT_SUCCESS` && in `FETCH_COINS_FRONT_FAILURE` set it to `false`.

Easiest you can get :)

**Comment by kazazor** [comment]
That way we'll also have an indication if we're updating the data in case we'll want to show some spinner somewhere in the future.. WDYT?

**Comment by kazazor** [comment]
Solved it here: https://github.com/kazazor/coinsmarket/pull/75 
:)

**Comment by OmriAharon** [comment]
Good idea, me likey!
